# Set up the prompt

autoload -Uz promptinit
promptinit

setopt histignorealldups sharehistory

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

###
### 
###
export PATH=$PATH:/usr/local/go/bin
export EDITOR=nvim
export VISUAL=nvim

source $HOME/dotfiles/unishell/alieses.sh
source $HOME/dotfiles/unishell/funcs.sh
[ -f $HOME/dotfiles/unishell/funcs_local.sh ] && source $HOME/dotfiles/unishell/funcs_local.sh

# github.com/sindresorhus/pure
fpath+=($HOME/dotfiles/zsh/pure)
autoload -U promptinit; promptinit
PURE_PROMPT_SYMBOL="#"
PURE_PROMPT_VICMD_SYMBOL="$"
prompt pure

# github.com/jeffreytse/zsh-vi-mode
source $HOME/dotfiles/zsh/zsh-vi-mode/zsh-vi-mode.plugin.zsh
